apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-model
  template:
    metadata:
      labels:
        app: iris-model
    spec:
      containers:
      - name: iris-container
        image: iris-fastapi
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
