apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  type: NodePort
  selector:
    app: iris-model
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
